### ISSUE TITLE
Babel-6 dependent

### ISSUE THREAD

**Issue by tomorrowevening** [silviopaganini/orbit-controls-es6#11]
Updating the [package.json](https://github.com/silviopaganini/orbit-controls-es6/blob/master/package.json)'s `dependencies` to `devDependencies` should avoid adding all the babel-6 node-modules when installing to allow for Babel 7 and higher

**Comment by silviopaganini** [comment]
pushed version 2.0.0 building with rollup... does it help?

**Comment by tomorrowevening** [comment]
nice work!
