### ISSUE TITLE
Check for camera type breaking

### ISSUE THREAD

**Issue by smcllns** [silviopaganini/orbit-controls-es6#2]
First, thanks for porting this over to es6 and hosting on npm!

Second, I have a bug (that I don't fully understand). No issues in development. But when I build from production with Webpack, I would get this error when I first try to zoom in or out, and zoom would become disabled: `WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.`

The OrbitControls js in three/examples/js checks for camera using:
`if (scope.object instanceof PerspectiveCamera)`
Indeed, so does your `build` version.

However, your `src` version seems to use: 
`if (scope.object.type === PerspectiveCamera.name)` 

This worked fine in development for me. But for whatever reason, when I build a production version with webpack, this would break. In this event, `scope.object.type = 'PerspectiveCamera'` but `PerspectiveCamera.name = 'Pt'`.

I forked your code and changed the comparison back to using `instanceof` and it works without a hitch. 

I don't have much time right now to isolate the cause further, but I was curious why you moved away from `instanceof` and if you can shed any light on this issue? Thanks!

**Comment by smcllns** [comment]
Heh, I just saw this PR:
https://github.com/silviopaganini/orbit-controls-es6/pull/1/commits/278cb63244d6cf09125186212928cc74be124b78

Given that the orbit controls regular library[1] uses instanceof, I think this PR is most likely the wrong change for this contributor's problem and this change should be reversed.

[1] https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/OrbitControls.js#L371

**Comment by smcllns** [comment]
Quicker solution for anyone else with the same issue -- just rollback back to the previous version:

`npm install --save orbit-controls-es6@1.0.8`

UPDATE: Actually, no, I apologize. Running 1.0.8 I discovered the issue the PR was addressing. Instead I'm using a fork with `if (scope.object.__proto__.isPerspectiveCamera) ...` as the check, and so far it's working.

**Comment by silviopaganini** [comment]
can you send the PR?
