### ISSUE TITLE
TypeError: _orbitControlsEs2.default is not a constructor

### ISSUE THREAD

**Issue by ghost** [silviopaganini/orbit-controls-es6#5]
I'm trying to follow your example syntax to assign an OrbitControls into a class member of an aurelia single page application.
This line,
`this._controls = new OrbitControls(this._camera, this._renderer.domElement);`

is receiving the above TypeError.

My import statement is similar (if not identical) to your example in the readme,
`import OrbitControls from 'orbit-controls-es6';`

**Comment by silviopaganini** [comment]
hmmmm should just work since it's just ES6... what presets are you using to compile your app?

**Comment by ghost** [comment]
Sorry I'm fairly new to Node/JavaScript development so could you let me know where I might find this? Somewhere in package.json or in one of the aurelia JSON files? When we build though we are using Aurelia (`au build`) or when we are just running (`au run --watch`).
