### ISSUE TITLE
Update build script for pre-compiled to ES5

### ISSUE THREAD

**Issue by tomorrowevening** [silviopaganini/orbit-controls-es6#9]
Updating _package.json_'s **build** script to:

`"build": "browserify --external three src/index.js > build/orbit-controls-es6.js"`

removes Three from the build making it way less than 1mb, but it's still wrapped in a function not apart of exports.default, so you'll have to manually remove the first line:

`(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){`

and the last line:

`},{"three":"three"}]},{},[1]);`

After that you're good to go, but this should be apart of the build process, because the updated [Babel](https://babeljs.io/repl/) generates something different from what you guys have.

**Comment by silviopaganini** [comment]
not sure i understand "you'll have to manually remove the first line and the last line". Is this first line the threejs module? 

also, maybe we should have a look at rollup or even webpack tree shaking for this.... what do you think?

**Comment by tomorrowevening** [comment]
yea, if we could remove the threejs module then we're all good. I'm unfamiliar with Rollup but it looks simpler than Webpack and might be more straight-forward with Tree Shaking.

**Comment by silviopaganini** [comment]
sorry for the delay, just built a version using rollup, let me know if that's fixed

**Comment by tomorrowevening** [comment]
yep! File-size went way down too, nice work!
